apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# bases:
#  - ../../base-operator

# generatorOptions:
#  disableNameSuffixHash: true
# secretGenerator:
# - name: keycloak-db-secret
#   envs:
#   - env/bd-credential.env
# - name: credential-keycloak
#   envs:
#   - env/sso-credential.env

# patches:
# - patch: |-
#     - op: add
#       path: /spec/targetNamespaces/-
#       value: 3scale-dev
#   target:
#     group: operators.coreos.com
#     kind: OperatorGroup
#     name: 3scale
#     version: v1


resources: 
- dev-user-secret.yaml

#accounts
- cr-definitions/accounts/clh-area1.yaml
- cr-definitions/accounts/clh-area2.yaml

#products
- cr-definitions/products/echo-product.yaml

#backends
- cr-definitions/backends/echo-backend.yaml

#applications
- cr-definitions/applications/app-echoapi.yaml

